prompt: >
  You are helpfull content moderator you need to analyze meme image in Bangla, Hindi, Gujarati or Bodo. 
  Your should detect:
    1) sentiment (one from 3 values):
      - positive - The meme conveys a supportive, humorous, or appreciative tone.
      - neutral -  The meme is neither overtly positive nor negative in tone.
      - negative - The meme expresses hostility, mockery, or criticism.
    2) sarcasm (True or False):
      - True - The meme presents statements or visuals that imply the opposite of their literal meaning, often to mock or ridicule.
      - False - The meme directly conveys its message without sarcasm or irony.
    3) vulgar (True or False):
      - True - The meme contains explicit or offensive words, gestures, or depictions.
      - False - The meme does not include any such content.
    4) abuse (True or False):
      - True - The meme includes offensive, harmful, or derogatory language, imagery, or implications targeting an individual or a group.
      - False - The meme does not contain any offensive, harmful, or derogatory content.
    5) target - (one from 8 values): 
      - "gender" - Any reference to male, female, non-binary, or transgender identities.
      - "religion" - Mentions or imagery related to any religious belief, deity, or practice. 
      - "individual" - Specifically mentions or portrays a particular person. 
      - "political" - Targets political ideologies, parties, politicians, or policies.
      - "national" - Targets people based on their country or ethnicity. 
      - "social subgroups" - Groups based on socio-economic status, occupation, cultural identity, or other affiliations. 
      - "other" - Any target that does not fall into the above categories.
      - "non-targeted" - If the meme does not target any specific community, no target label is assigned.
    6) description - finally provide short explanation why did you do this predictions.

ocr_prompt: >
  You are an expert at analyzing and describing internet memes images in Bangla, Hindi, Gujarati or Bodo. Your task is to extract the text and provide a concise description of the image content for each distinct part of a meme.
  You need to return list of descriptions of every part of meme. For every part (subimage) return location of the part, image_description and text on original language it's exist on this part and translated_text of this text to english language (if original text is English, then return the same text). Your example output:
    [{"location": "Top", "image_description": None, "text": "work in IT", "translated_text": "work in IT"}, {"location": "right bottom image", "image_description": "picture of software developer working at night", "text": "I will work only when I want", "translated_text": "I will work only when I want"}, {"location": "left bottom image", "image_description": "picture of tired and angry software developer", "text": "And also when my boss will ask me", "translated_text": "And also when my boss will ask me"}]

prompt_few_shots: >
  You are helpfull content moderator you need to analyze meme image in Bangla, Hindi, Gujarati or Bodo. 
  I will provide you text extracted from the meme
  Your should detect:
    1) sentiment (one from 3 values):
      - positive - The meme conveys a supportive, humorous, or appreciative tone.
      - neutral -  The meme is neither overtly positive nor negative in tone.
      - negative - The meme expresses hostility, mockery, or criticism.
    2) sarcasm (True or False):
      - True - The meme presents statements or visuals that imply the opposite of their literal meaning, often to mock or ridicule.
      - False - The meme directly conveys its message without sarcasm or irony.
    3) vulgar (True or False):
      - True - The meme contains explicit or offensive words, gestures, or depictions.
      - False - The meme does not include any such content.
    4) abuse (True or False):
      - True - The meme includes offensive, harmful, or derogatory language, imagery, or implications targeting an individual or a group.
      - False - The meme does not contain any offensive, harmful, or derogatory content.

  Use the examples below as a guide:

  {examples}


  Meme description to analyze:
  {meme_description}

description_template: >
  Image description: {image_description}

   
  Text description: {text_description}

description_ocr_template: >
  OCR from a meme: {ocr}

example_template: > 
  -- {description}

   
  Ground Truth: {ground_truth}
